import { TypeDefault } from '@assets/styles/themes/TypeDefault';

import * as Styles from './styles';

const BoxDefault: React.FC<TypeDefault> = ({
  bgcolor,
  bgtext,
  fontSize,
  direction,
  jcontent,
  aitems,
  padding,
  paddingX,
  paddingY,
  margin,
  marginTop,
  marginBottom,
  marginX,
  marginY,
  xsmall,
  small,
  medium,
  large,
  xlarge,
  xxlarge,
  isVisibility,
  isDisplay,
  height,
  width,
  media,
  gap,
  radius,
  radiusTopLeft,
  radiusTopRight,
  radiusBottomLeft,
  radiusBottomRight,
  isGridRepeat,
  display,
  isBorder,
  border,
  as,
  ...props
}) => {
  return (
    <Styles.BoxDefaultStyle
      bgtext={bgtext}
      bgcolor={bgcolor}
      textcolor={props.textcolor}
      fontSize={fontSize}
      direction={direction}
      jcontent={jcontent}
      aitems={aitems}
      xsmall={xsmall}
      small={small}
      medium={medium}
      large={large}
      xlarge={xlarge}
      xxlarge={xxlarge}
      height={height}
      width={width}
      media={media}
      padding={padding}
      paddingX={paddingX}
      paddingY={paddingY}
      margin={margin}
      marginTop={marginTop}
      marginBottom={marginBottom}
      marginX={marginX}
      marginY={marginY}
      radius={radius}
      radiusTopLeft={radiusTopLeft}
      radiusTopRight={radiusTopRight}
      radiusBottomLeft={radiusBottomLeft}
      radiusBottomRight={radiusBottomRight}
      gap={gap}
      isVisibility={isVisibility}
      isDisplay={isDisplay}
      display={display}
      isBorder={isBorder}
      border={border}
      as={as}
      isGridRepeat={isGridRepeat}
      isImgRadius={props.isImgRadius}
      isBoxShadow={props.isBoxShadow}
      flexWrap={props.flexWrap}
      flexGrow={props.flexGrow}
      alignSelf={props.alignSelf}
      isGridRow={props.isGridRow}
      gridRowStart={props.gridRowStart}
      gridRowStartSpan={props.gridRowStartSpan}
      gridRowEnd={props.gridRowEnd}
      gridRowEndSpan={props.gridRowEndSpan}
      isGridColumn={props.isGridColumn}
      gridColumnStart={props.gridColumnStart}
      gridColumnStartSpan={props.gridColumnStartSpan}
      gridColumnEnd={props.gridColumnEnd}
      gridColumnEndSpan={props.gridColumnEndSpan}
      gridTemplateRows={props.gridTemplateRows}
      gridTemplateColumns={props.gridTemplateColumns}
      gridArea={props.gridArea}
      iconBgcolor={props.iconBgcolor}
      iconColor={props.iconColor}
      iconSize={props.iconSize}
      isAfter={props.isAfter}
      isBefore={props.isBefore}
      position={props.position}
      left={props.left}
      right={props.right}
      top={props.top}
      bottom={props.bottom}
      zIndex={props.zIndex}
      flexBasis={props.flexBasis}
      isBorderDefault={props.isBorderDefault}
      borderWidth={props.borderWidth}
      borderStyle={props.borderStyle}
      borderColor={props.borderColor}
      borderTopColor={props.borderTopColor}
      borderTopStyle={props.borderTopStyle}
      borderTopWidth={props.borderTopWidth}
      borderRightColor={props.borderRightColor}
      borderRightStyle={props.borderRightStyle}
      borderRightWidth={props.borderRightWidth}
      borderBottomColor={props.borderBottomColor}
      borderBottomStyle={props.borderBottomStyle}
      borderBottomWidth={props.borderBottomWidth}
      borderLeftColor={props.borderLeftColor}
      borderLeftStyle={props.borderLeftStyle}
      borderLeftWidth={props.borderLeftWidth}
      borderImageSource={props.borderImageSource}
      borderImageSlice={props.borderImageSlice}
      borderImageWidth={props.borderImageWidth}
      borderImageOutset={props.borderImageOutset}
      borderImageRepeat={props.borderImageRepeat}
      gridColumnsDefault={props.gridColumnsDefault}
    >
      {props.children}
    </Styles.BoxDefaultStyle>
  );
};

export { BoxDefault };
