// import { ReactComponent as ImgDelete } from '@assets/image/delete.svg';
// import { ReactComponent as ImgEntregar } from '@assets/image/entregar.svg';
// import { ReactComponent as ImgBrand } from '@assets/image/brand.svg';
export const ImgBrand = './src/assets/image/brand.svg';
export const HomeImage = './src/assets/image/homeImage.svg';
export const ImgCoffeeAgua = './src/assets/image/coffee_agua.svg';
export const ImgDolar = './src/assets/image/dolar.svg';
export const ImgDebito = './src/assets/image/debito.svg';
export const ImgCredito = './src/assets/image/credito.svg';
export const ImgDinheiro = './src/assets/image/dinheiro.svg';
export const ImgLocation = './src/assets/image/location.svg';
export const ImgDelete = './src/assets/image/delete.svg';
export const ImgEntregar = './src/assets/image/entregar.svg';
export const ImgTimer = './src/assets/image/timer.svg';
export const ImgClock = './src/assets/image/clock.svg';
export const ImgDolares = './src/assets/image/dolares.svg';
export const ImgCoffeer = './src/assets/image/coffeer.svg';
export const ImgCard = './src/assets/image/card.svg';
export const ImgPagote = './src/assets/image/pacote.svg';
export const ImgLocal = './src/assets/image/local.svg';
export const ImgCardTop = './src/assets/image/cardTop.svg';
export const ImgPost41 = './src/assets/image/posts/4.1.jpg';
export const ImgPost42 = './src/assets/image/posts/4.2.jpg';
export const ImgPost43 = './src/assets/image/posts/4.3.jpg';
export const ImgPost81 = './src/assets/image/posts/8.1.jpg';
export const ImgPost82 = './src/assets/image/posts/8.2.jpg';
export const ImgPost83 = './src/assets/image/posts/8.3.jpg';
export const ImgPost121 = './src/assets/image/posts/12.1.jpg';
export const ImgPost122 = './src/assets/image/posts/12.2.jpg';
export const ImgPost123 = './src/assets/image/posts/12.3.jpg';
export const ImgPost124 = './src/assets/image/posts/12.4.jpg';
export const ImgPost125 = './src/assets/image/posts/12.5.jpg';
export const ImgPost22 = './src/assets/image/posts/22.jpg';
export const ImgGrid221 = './src/assets/image/grid/2.1.jpg';
export const ImgGrid222 = './src/assets/image/grid/2.2.jpg';
export const ImgGrid223 = './src/assets/image/grid/2.3.jpg';
export const ImgGrid224 = './src/assets/image/grid/2.4.jpg';
export const ImgGrid71 = './src/assets/image/grid/7.1.jpg';
export const ImgGrid72 = './src/assets/image/grid/7.2.jpg';
export const ImgGrid73 = './src/assets/image/grid/7.3.jpg';
export const ImgGrid74 = './src/assets/image/grid/7.4.jpg';
export const ImgGrid75 = './src/assets/image/grid/7.5.jpg';
export const ImgGrid76 = './src/assets/image/grid/7.6.jpg';
export const ImgGrid131 = './src/assets/image/grid/13.1.jpg';
export const ImgGrid132 = './src/assets/image/grid/13.2.jpg';
export const ImgGrid133 = './src/assets/image/grid/13.3.jpg';
export const ImgGrid134 = './src/assets/image/grid/13.4.jpg';
export const ImgGrid135 = './src/assets/image/grid/13.5.jpg';
export const ImgGrid136 = './src/assets/image/grid/13.6.jpg';
export const ImgGrid137 = './src/assets/image/grid/13.7.jpg';
export const ImgGrid138 = './src/assets/image/grid/13.8.jpg';
export const ImgGrid139 = './src/assets/image/grid/13.9.jpg';
export const ImgGrid1310 = './src/assets/image/grid/13.10.jpg';
export const ImgGridAbount1 = './src/assets/image/grid/abount-1.jpg';
export const ImgGridAbount2 = './src/assets/image/grid/abount-2.jpg';
export const ImgGridAbount3 = './src/assets/image/grid/abount-3.jpg';
export const ImgGridBagWomen = './src/assets/image/grid/bag-women.jpg';
export const ImgGridEl = './src/assets/image/grid/el.jpg';
export const ImgGridJacket = './src/assets/image/grid/jacket.jpg';
export const ImgGridSignUp = './src/assets/image/grid/sign-up.jpg';
export const ImgGridSneakersWomen =
  './src/assets/image/grid/sneakers-women.jpg';
export const ImgGridSweaterWomens = './src/assets/image/grid/sweater-women.jpg';
export const ImgGridSunglasses = './src/assets/image/grid/sunglasses.jpg';
export const ImgGridSweater = './src/assets/image/grid/sweater.jpg';
export const ImgGridShirt = './src/assets/image/grid/t-shirt.jpg';
export const ImgGridShirtMen = './src/assets/image/grid/t-shirt-men.jpg';
export const ImgGridShirtWomen = './src/assets/image/grid/t-shirt-women.jpg';
// export { ImgEntregar, ImgDelete, ImgBrand };

// export { ReactComponent as ReactjsTrail } from "./reactjs.svg";
