import { TypeDefault } from '@assets/styles/themes/TypeDefault';
import * as Styles from './styles';

const TextDefault: React.FC<TypeDefault> = ({ children, ...props }) => {
  return (
    <>
      <Styles.ContainerTextDefault
        as={props.as}
        beforeDefault={props.beforeDefault}
        afterDefault={props.afterDefault}
        effectDefault={props.effectDefault}
        effectHoverDefault={props.effectHoverDefault}
        effectHoverBeforeDefault={props.effectHoverBeforeDefault}
        effectHoverAfterDefault={props.effectHoverAfterDefault}
        heightStaticDefault={props.heightStaticDefault}
        heightDynamicDefault={props.heightDynamicDefault}
        widthStaticDefault={props.widthStaticDefault}
        widthDynamicDefault={props.widthDynamicDefault}
        fontSizeStaticDefault={props.fontSizeStaticDefault}
        fontSizeDynamicDefault={props.fontSizeDynamicDefault}
        textTransformDefault={props.textTransformDefault}
        textAlignDefault={props.textAlignDefault}
        textTitleDefault={props.textTitleDefault}
        textParagraphDefault={props.textParagraphDefault}
        fontFamilyDefault={props.paddingTopDefault}
        fontStyleDefault={props.fontStyleDefault}
        fontLineHeightDefault={props.fontLineHeightDefault}
        textDecoretionlineThrough={props.textDecoretionlineThrough}
        borderDefault={props.borderDefault}
        borderTopDefault={props.borderTopDefault}
        borderRightDefault={props.borderTopDefault}
        borderBottomDefault={props.borderBottomDefault}
        borderLeftDefault={props.borderLeftDefault}
        borderRadiusDefault={props.borderRadiusDefault}
        borderRadiusTopRightDefault={props.borderRadiusTopRightDefault}
        borderRadiusTopLeftDefault={props.borderRadiusTopLeftDefault}
        borderRadiusBottomRightDefault={props.borderRadiusBottomRightDefault}
        borderRadiusBottomLeftDefault={props.borderRadiusBottomLeftDefault}
        paddingDefault={props.paddingDefault}
        paddingStaticDefault={props.paddingStaticDefault}
        paddingStaticXDefault={props.paddingStaticXDefault}
        paddingStaticYDefault={props.paddingStaticYDefault}
        paddingDynamicDefault={props.paddingDynamicDefault}
        paddingDynamicXDefault={props.paddingDynamicXDefault}
        paddingDynamicYDefault={props.paddingDynamicYDefault}
        paddingTopDefault={props.paddingTopDefault}
        paddingRightDefault={props.paddingRightDefault}
        paddingBottomDefault={props.paddingBottomDefault}
        paddingLeftDefault={props.paddingLeftDefault}
        marginStaticDefault={props.marginStaticDefault}
        marginStaticXDefault={props.marginStaticXDefault}
        marginStaticYDefault={props.marginStaticYDefault}
        marginDynamicDefault={props.marginDynamicDefault}
        marginDynamicXDefault={props.marginDynamicXDefault}
        marginDynamicYDefault={props.marginDynamicYDefault}
        marginTopDefault={props.marginTopDefault}
        marginRightDefault={props.marginRightDefault}
        marginBottomDefault={props.marginBottomDefault}
        marginLeftDefault={props.marginLeftDefault}
        flexDirectionDefault={props.flexDirectionDefault}
        alignSelfDefault={props.alignSelfDefault}
        flexGapDefault={props.flexGapDefault}
        justifyContentDefault={props.justifyContentDefault}
        alignItemsDefault={props.alignItemsDefault}
        flexBasisDefault={props.flexBasisDefault}
        flexGrowDefault={props.flexGrowDefault}
        zIndexDefault={props.zIndexDefault}
        imparDefault={props.imparDefault}
        parDefault={props.parDefault}
        boxShadowDefault={props.boxShadowDefault}
        displayDefault={props.displayDefault}
        backgroundColorDefault={props.backgroundColorDefault}
        backgroundLinearGradientDefault={props.backgroundLinearGradientDefault}
        textColorDefault={props.textColorDefault}
        iconDefault={props.iconDefault}
      >
        {children}
      </Styles.ContainerTextDefault>
    </>
  );
};

export { TextDefault };
