import { TypeDefault } from '@assets/styles/themes/TypeDefault';
import * as Styled from './styles';

const HeadingDefault: React.FC<TypeDefault> = ({
  children,
  bgcolor,
  bgtext,
  as = 'h1',
  fontSize,
  isUppercase = false,
  fontFamily,
  fontWeight,
  lineHeight,
  fontStyle,
  padding,
  paddingX,
  paddingY,
  margin,
  marginX,
  marginY,
  radius,
  radiusTopLeft,
  radiusTopRight,
  radiusBottomLeft,
  radiusBottomRight,
  gap,
  flexWrap,
  direction,
  aitems,
  jcontent,
  ...props
}) => {
  return (
    <Styled.HeadingDefaultContainer
      fontSize={fontSize}
      fontStyle={fontStyle}
      as={as}
      bgcolor={bgcolor}
      textcolor={props.textcolor}
      bgtext={bgtext}
      isUppercase={isUppercase}
      isTextDecoretionLineThrough={props.isTextDecoretionLineThrough}
      fontFamily={fontFamily}
      fontWeight={fontWeight}
      lineHeight={lineHeight}
      padding={padding}
      paddingX={paddingX}
      paddingY={paddingY}
      margin={margin}
      marginX={marginX}
      marginY={marginY}
      radius={radius}
      radiusTopLeft={radiusTopLeft}
      radiusTopRight={radiusTopRight}
      radiusBottomLeft={radiusBottomLeft}
      radiusBottomRight={radiusBottomRight}
      gap={gap}
      flexWrap={flexWrap}
      direction={direction}
      aitems={aitems}
      jcontent={jcontent}
      textAling={props.textAling}
      width={props.width}
      height={props.height}
      isGridRow={props.isGridRow}
      gridRowStart={props.gridRowStart}
      gridRowStartSpan={props.gridRowStartSpan}
      gridRowEnd={props.gridRowEnd}
      gridRowEndSpan={props.gridRowEndSpan}
      isGridColumn={props.isGridColumn}
      gridColumnStart={props.gridColumnStart}
      gridColumnStartSpan={props.gridColumnStartSpan}
      gridColumnEnd={props.gridColumnEnd}
      gridColumnEndSpan={props.gridColumnEndSpan}
      isMarginCustom={props.isMarginCustom}
      marginStaticX={props.marginStaticX}
      marginStaticY={props.marginStaticY}
      position={props.position}
      fsd={props.fsd}
      fsdcalc={props.fsdcalc}
      fss={props.fss}
      psx={props.psx}
      psy={props.psy}
      pst={props.pst}
      psb={props.psb}
      psl={props.psl}
      psr={props.psr}
      paddingDynamicX={props.paddingDynamicX}
      paddingDynamicY={props.paddingDynamicY}
      paddingDynamic={props.paddingDynamic}
      paddingStatic={props.paddingStatic}
      paddingStaticY={props.paddingStaticY}
      paddingStaticX={props.paddingStaticX}
      paddingTop={props.paddingTop}
      paddingBottom={props.paddingBottom}
      paddingLeft={props.paddingLeft}
      paddingRight={props.paddingRight}
      marginDynamicX={props.marginDynamicX}
      marginDynamicY={props.marginDynamicY}
      marginDynamic={props.marginDynamic}
      marginStatic={props.marginStatic}
      marginTop={props.marginTop}
      marginBottom={props.marginBottom}
      marginLeft={props.marginLeft}
      marginRight={props.marginRight}
      fontSizeDynamic={props.fontSizeDynamic}
      fontSizeStatic={props.fontSizeStatic}
      borderDefault={props.borderDefault}
      borderDefaultTop={props.borderDefaultTop}
      borderDefaultRight={props.borderDefaultRight}
      borderDefaultBottom={props.borderDefaultBottom}
      borderDefaultLeft={props.borderDefaultLeft}
      afterDefault={props.afterDefault}
      beforeDefault={props.beforeDefault}
    >
      {children}
    </Styled.HeadingDefaultContainer>
  );
};

export { HeadingDefault };
