import { TypeDefault } from '@assets/styles/themes/TypeDefault';
import * as Styles from './styles';

const ImgDefault: React.FC<TypeDefault> = ({ ...props }) => {
  return (
    <Styles.FigureDefaultContainer
      src={props.src}
      alt={props.alt}
      radius={props.radius}
      isRadiusTop={props.isRadiusTop}
      isRadiusBottom={props.isRadiusBottom}
      isAfter={props.isAfter}
      afterClipPath={props.afterClipPath}
      afterPosition={props.afterPosition}
      afterBackgroundColor={props.afterBackgroundColor}
      afterBackgroundImg={props.afterBackgroundImg}
      afterWidth={props.afterWidth}
      afterHeight={props.afterHeight}
      afterLeft={props.afterLeft}
      afterRight={props.afterRight}
      afterTop={props.afterTop}
      afterBottom={props.afterBottom}
      afterZindex={props.afterZindex}
      isBefore={props.isBefore}
      beforeClipPath={props.beforeClipPath}
      beforePosition={props.beforePosition}
      beforeBackgroundColor={props.beforeBackgroundColor}
      beforeBackgroundImg={props.beforeBackgroundImg}
      beforeWidth={props.beforeWidth}
      beforeHeight={props.beforeHeight}
      beforeLeft={props.beforeLeft}
      beforeRight={props.beforeRight}
      beforeTop={props.beforeTop}
      beforeBottom={props.beforeBottom}
      beforeZindex={props.beforeZindex}
      isPosition={props.isPosition}
      position={props.position}
      left={props.left}
      right={props.right}
      top={props.top}
      bottom={props.bottom}
      display={props.display}
      flexBasis={props.flexBasis}
      direction={props.direction}
      jcontent={props.jcontent}
      aitems={props.aitems}
      zIndex={props.zIndex}
      gridColumnsDefault={props.gridColumnsDefault}
      gridRows={props.gridRows}
      positionDefault={props.positionDefault}
      afterDefault={props.afterDefault}
      beforeDefault={props.beforeDefault}
      width={props.width}
      height={props.height}
    >
      <Styles.ImgDefaultContainer
        loading='lazy'
        src={props.src}
        alt={props.alt}
        radius={props.radius}
        isRadiusTop={props.isRadiusTop}
        isRadiusBottom={props.isRadiusBottom}
        isHeight={props.isHeight}
        heightR={props.heightR}
        heightP={props.heightP}
        heightPX={props.heightPX}
        heightVW={props.heightVW}
        heightVH={props.heightVH}
        heightCalc={props.heightCalc}
        isWidth={props.isWidth}
        widthR={props.widthR}
        widthP={props.widthP}
        widthPX={props.widthPX}
        widthVW={props.widthVW}
        widthVH={props.widthVH}
        widthCalc={props.widthCalc}
        isAfter={props.isAfter}
        isAfterTransform={props.isAfterTransform}
        isTransform={props.isTransform}
        afterClipPath={props.afterClipPath}
        afterPosition={props.afterPosition}
        afterBackgroundColor={props.afterBackgroundColor}
        afterBackgroundImg={props.afterBackgroundImg}
        afterLeft={props.afterLeft}
        afterRight={props.afterRight}
        afterTop={props.afterTop}
        afterBottom={props.afterBottom}
        afterZindex={props.afterZindex}
        isBefore={props.isBefore}
        isBeforeTransform={props.isBeforeTransform}
        beforeClipPath={props.beforeClipPath}
        beforePosition={props.beforePosition}
        beforeBackgroundColor={props.beforeBackgroundColor}
        beforeBackgroundImg={props.beforeBackgroundImg}
        beforeLeft={props.beforeLeft}
        beforeRight={props.beforeRight}
        beforeTop={props.beforeTop}
        beforeBottom={props.beforeBottom}
        beforeZindex={props.beforeZindex}
        isPosition={props.isPosition}
        position={props.position}
        left={props.left}
        right={props.right}
        top={props.top}
        bottom={props.bottom}
        zIndex={props.zIndex}
        borderRadius={props.borderRadius}
        width={props.width}
        height={props.height}
        effectDefault={props.effectDefault}
      />
    </Styles.FigureDefaultContainer>
  );
};

export { ImgDefault };
